import { Company, Trigger } from '../types'

const co = (
  id: string,
  ticker: string,
  name: string,
  market: string,
  country: string,
  currency: string,
): Company => ({ _id: id, ticker, name, market, country, currency })

export const COMPANIES: Record<string, Company> = {
  OCGN:   co('ocgn',   'OCGN',   'Ocugen',       'NASDAQ',           'US', 'USD'),
  MNOV:   co('mnov',   'MNOV',   'MediciNova',    'NASDAQ',           'US', 'USD'),
  EGET:   co('eget',   'EGET',   'Egetis',        'Nasdaq Stockholm', 'SE', 'SEK'),
  NIMBU:  co('nimbu',  'NIMBU',  'Nimbus Group',  'Nasdaq Stockholm', 'SE', 'SEK'),
  SIMRIS: co('simris', 'SIMRIS', 'Simris Group',  'Nasdaq Stockholm', 'SE', 'SEK'),
  PANS:   co('pans',   'PANS',   'Parans',        'Nasdaq Stockholm', 'SE', 'SEK'),
  TAUR:   co('taur',   'TAUR',   'Taurus',        'Nasdaq Stockholm', 'SE', 'SEK'),
  CLEM:   co('clem',   'CLEM',   'Clemondo',      'Nasdaq Stockholm', 'SE', 'SEK'),
  SPEC:   co('spec',   'SPEC',   'Spectrumone',   'Nasdaq Stockholm', 'SE', 'SEK'),
  XINT:   co('xint',   'XINT',   'Xintela',       'Nasdaq Stockholm', 'SE', 'SEK'),
  SIVR:   co('sivr',   'SIVR',   'Sivers',        'Nasdaq Stockholm', 'SE', 'SEK'),
  ONCO:   co('onco',   'ONCO',   'Oncopeptides',  'Nasdaq Stockholm', 'SE', 'SEK'),
}

export const MOCK_TRIGGERS: Trigger[] = [
  {
    _id: 'ocugen-1',
    title: 'Phase 3 top-line data for OCU400 in retinitis pigmentosa expected Q4 2026',
    summary:
      'Ocugen reports that its Phase 3 "liMeLiGhT" trial for OCU400 is nearing full enrollment. Top-line results are expected in Q4 2026. The trial targets multiple genetic mutations with a single gene therapy, making positive efficacy data a potentially major stock-moving event. Ocugen also plans to submit BLA/MAA applications in 2026 if data supports approval.',
    company: COMPANIES.OCGN,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-05-26',
      dateExpected: '2026-12-31',
      dateExpectedUpdate: '2026-12-31',
    },
    prices: { priceAtAdded: 1.20, priceAtStatusChanged: 1.20 },
    source: { link: '#', text: 'Official Announcement' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'medicinova-1',
    title: 'Full randomization in COMBAT-ALS Phase 2/3 trial & top-line data expected in 2026',
    summary:
      'MediciNova has completed enrollment of 234 patients in its Phase 2/3 COMBAT-ALS trial for MN-166 (ibudilast). Top-line results are expected by end of 2026. The data was presented at the 36th International ALS/MND Symposium. MN-166 holds FDA Orphan Drug and Fast Track designations.',
    company: COMPANIES.MNOV,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-05-25',
      dateExpected: '2026-12-31',
      dateExpectedUpdate: '2026-12-31',
    },
    prices: { priceAtAdded: 2.10, priceAtStatusChanged: 2.10 },
    source: { link: '#', text: 'Official Announcement' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'egetis-1',
    title: 'Emcitate NDA application completed in the U.S., decision expected September 2026',
    summary:
      'Egetis has completed the rolling NDA in the US for Emcitate (tiratricol) for MCT8 deficiency. A regulatory decision is expected in September 2026. Emcitate has received Fast Track, Breakthrough Therapy, and Rare Pediatric Disease designations. Priority Review has been requested, meaning FDA review is to be completed within six months of the 60-day validation period.',
    company: COMPANIES.EGET,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-05-24',
      dateExpected: '2026-09-30',
      dateExpectedUpdate: '2026-09-30',
    },
    prices: { priceAtAdded: 8.50, priceAtStatusChanged: 8.50 },
    source: { link: '#', text: 'Official Announcement' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'nimbus-1',
    title: 'Nimbus Group Receives FMV Approval for MSMB 200 Ahead of Series Production',
    summary:
      'Nimbus Group and Svekon have received approval from the Swedish Defence Materiel Administration (FMV) following sea trials for the workboat MSMB 200. Series production is expected to begin later this year. The agreement with FMV is valued at up to SEK 400 million over 15 years.',
    company: COMPANIES.NIMBU,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-05-23',
      dateExpected: '2026-12-31',
      dateExpectedUpdate: '2026-12-31',
    },
    prices: { priceAtAdded: 24.50, priceAtStatusChanged: 24.50 },
    source: { link: '#', text: 'Official Announcement' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'simris-1',
    title: 'Simris Group Signs MoU for Potential Divestment of Hammenhög Microalgae Assets',
    summary:
      'Simris Group has entered into an MoU with Immunrise Biocontrol France regarding a potential divestment of its microalgae production assets in Hammenhög, Sweden. A firm and binding offer is expected no later than 1 March 2026. A definitive agreement is targeted by 31 March 2026, subject to due diligence.',
    company: COMPANIES.SIMRIS,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-05-22',
      dateExpected: '2026-03-31',
      dateExpectedUpdate: '2026-03-31',
    },
    prices: { priceAtAdded: 0.12, priceAtStatusChanged: 0.12 },
    source: { link: '#', text: 'Official Announcement' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'parans-1',
    title: 'FDA Market Approval for daylighting systems in healthcare facilities',
    summary:
      'Decision regarding marketing authorization for Parans daylighting systems in US healthcare facilities. The application was submitted in late 2023 with a Q4 2024 decision window.',
    company: COMPANIES.PANS,
    type: 'expected',
    status: 'cancelled',
    dates: {
      dateAdded: '2023-12-01',
      dateExpected: '2024-12-31',
      dateExpectedUpdate: '2024-12-31',
      dateStatusChanged: '2025-01-15',
    },
    prices: { priceAtAdded: 0.45, priceAtStatusChanged: 0.38 },
    source: { link: '#', text: 'Official Press Release' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'parans-2',
    title: 'Middle East Distribution Expansion — formal agreement with regional partners',
    summary:
      'Formal agreement signed with regional partners for large-scale installation in Dubai. The deal marks a significant step in Parans international expansion strategy.',
    company: COMPANIES.PANS,
    type: 'expected',
    status: 'triggered',
    dates: {
      dateAdded: '2023-11-10',
      dateExpected: '2023-11-15',
      dateExpectedUpdate: '2023-11-15',
      dateStatusChanged: '2023-11-15',
    },
    prices: { priceAtAdded: 0.50, priceAtStatusChanged: 0.68 },
    source: { link: '#', text: 'Press Release' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'taurus-1',
    title: 'Phase II clinical trial readout for bovine growth hormones',
    summary:
      'Anticipated readout for Phase II clinical trials of Taurus bovine growth hormone therapy. Results are expected in Q1 2025 and would be a key catalyst for the stock.',
    company: COMPANIES.TAUR,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-05-15',
      dateExpected: '2025-03-31',
      dateExpectedUpdate: '2025-03-31',
    },
    prices: { priceAtAdded: 15.40, priceAtStatusChanged: 15.40 },
    source: { link: '#', text: 'ClinicalTrials.gov' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'clemondo-1',
    title: 'Full distribution of sustainable cleaning products across Scandinavian retail chains',
    summary:
      'Clemondo completes rollout of its sustainable cleaning product line to major Scandinavian retail chains. The launch covers Sweden, Norway, and Denmark and marks the culmination of an 18-month distribution agreement.',
    company: COMPANIES.CLEM,
    type: 'expected',
    status: 'triggered',
    dates: {
      dateAdded: '2024-01-10',
      dateExpected: '2024-02-01',
      dateExpectedUpdate: '2024-02-01',
      dateStatusChanged: '2024-02-01',
    },
    prices: { priceAtAdded: 1.80, priceAtStatusChanged: 2.15 },
    source: { link: '#', text: 'Corporate Website' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'spectrumone-1',
    title: 'Quarterly Earnings Update and revised full-year guidance',
    summary:
      'Spectrumone quarterly financial results including revised guidance for the next fiscal year. The report was delayed from the initial February target, now expected in March 2024.',
    company: COMPANIES.SPEC,
    type: 'expected_update',
    status: 'delayed',
    dates: {
      dateAdded: '2024-01-20',
      dateExpected: '2024-02-15',
      dateExpectedUpdate: '2024-03-15',
    },
    prices: { priceAtAdded: 0.85, priceAtStatusChanged: 0.72 },
    source: { link: '#', text: 'Investor Relations' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'xintela-1',
    title: 'Initiation of first human trial of XSTEM-OA in osteoarthritis patients',
    summary:
      'Xintela opens recruitment for the first human trial of XSTEM-OA in patients with osteoarthritis. The trial is the first-in-human study for the company\'s stem cell therapy platform.',
    company: COMPANIES.XINT,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-03-01',
      dateExpected: '2024-09-30',
      dateExpectedUpdate: '2024-09-30',
    },
    prices: { priceAtAdded: 0.42, priceAtStatusChanged: 0.42 },
    source: { link: '#', text: 'Scientific Journal' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'sivers-1',
    title: '5G Infrastructure Contract with major European telecommunications provider',
    summary:
      'Sivers signs a major chip supply agreement with a European telecommunications provider for 5G infrastructure deployment. The contract is valued at an undisclosed amount and covers multi-year delivery.',
    company: COMPANIES.SIVR,
    type: 'expected',
    status: 'triggered',
    dates: {
      dateAdded: '2024-07-20',
      dateExpected: '2024-08-10',
      dateExpectedUpdate: '2024-08-10',
      dateStatusChanged: '2024-08-10',
    },
    prices: { priceAtAdded: 6.80, priceAtStatusChanged: 8.40 },
    source: { link: '#', text: 'Industry News' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'onco-1',
    title: 'CHMP final recommendation for expanded use of Pepaxti in relapsed multiple myeloma',
    summary:
      'The CHMP is expected to issue its final recommendation for expanded use of Pepaxti (melphalan flufenamide) in relapsed/refractory multiple myeloma. A positive opinion would strengthen the European commercial case for Oncopeptides.',
    company: COMPANIES.ONCO,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-09-05',
      dateExpected: '2024-12-31',
      dateExpectedUpdate: '2024-12-31',
    },
    prices: { priceAtAdded: 3.10, priceAtStatusChanged: 3.10 },
    source: { link: '#', text: 'EMA Announcement' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'onco-2',
    title: 'FDA Advisory Committee meeting to discuss post-approval data for Pepaxti',
    summary:
      'Advisory committee meeting to evaluate post-approval data supporting continued US marketing of Pepaxti. The outcome will inform the FDA\'s decision on the full label indication.',
    company: COMPANIES.ONCO,
    type: 'expected',
    status: 'on_time',
    dates: {
      dateAdded: '2024-10-01',
      dateExpected: '2024-11-20',
      dateExpectedUpdate: '2024-11-20',
    },
    prices: { priceAtAdded: 4.20, priceAtStatusChanged: 4.20 },
    source: { link: '#', text: 'FDA Notice' },
    reviewStatus: { status: 'approved' },
  },
  {
    _id: 'onco-3',
    title: 'Q2 Report — commercial ramp-up of Pepaxti in Germany',
    summary:
      'Live webcast discussing Q2 financial results with a focus on the commercial ramp-up of Pepaxti in Germany. Analysts are watching for unit uptake figures and revised full-year guidance.',
    company: COMPANIES.ONCO,
    type: 'expected_update',
    status: 'triggered',
    dates: {
      dateAdded: '2024-08-10',
      dateExpected: '2024-08-15',
      dateExpectedUpdate: '2024-08-15',
      dateStatusChanged: '2024-08-15',
    },
    prices: { priceAtAdded: 2.45, priceAtStatusChanged: 5.80 },
    source: { link: '#', text: 'Corporate Webcast' },
    reviewStatus: { status: 'approved' },
  },
]
